[font]
size = 12.0

[font.bold]
family = "Juisee SZIS"
style = "Bold"

[font.bold_italic]
family = "Juisee SZIS"
style = "BoldItalic"

[font.italic]
family = "Juisee SZIS"
style = "RegularItalic"

[font.normal]
family = "Juisee SZIS"
style = "Regular"
